In [3]:
import pandas as pd
import numpy as np
from sklearn.datasets import load_iris

import matplotlib.pyplot as plt
import seaborn as sns
# import plotly as py
# py.offline.init_notebook_mode(connected=True)
%matplotlib inline

In [6]:
iris = load_iris()

In [7]:
x=iris.data
y=iris.target
print(x,y)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.1 1.5 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

In [10]:
data=np.c_[x,y]
print(data)

[[5.1 3.5 1.4 0.2 0. ]
 [4.9 3.  1.4 0.2 0. ]
 [4.7 3.2 1.3 0.2 0. ]
 [4.6 3.1 1.5 0.2 0. ]
 [5.  3.6 1.4 0.2 0. ]
 [5.4 3.9 1.7 0.4 0. ]
 [4.6 3.4 1.4 0.3 0. ]
 [5.  3.4 1.5 0.2 0. ]
 [4.4 2.9 1.4 0.2 0. ]
 [4.9 3.1 1.5 0.1 0. ]
 [5.4 3.7 1.5 0.2 0. ]
 [4.8 3.4 1.6 0.2 0. ]
 [4.8 3.  1.4 0.1 0. ]
 [4.3 3.  1.1 0.1 0. ]
 [5.8 4.  1.2 0.2 0. ]
 [5.7 4.4 1.5 0.4 0. ]
 [5.4 3.9 1.3 0.4 0. ]
 [5.1 3.5 1.4 0.3 0. ]
 [5.7 3.8 1.7 0.3 0. ]
 [5.1 3.8 1.5 0.3 0. ]
 [5.4 3.4 1.7 0.2 0. ]
 [5.1 3.7 1.5 0.4 0. ]
 [4.6 3.6 1.  0.2 0. ]
 [5.1 3.3 1.7 0.5 0. ]
 [4.8 3.4 1.9 0.2 0. ]
 [5.  3.  1.6 0.2 0. ]
 [5.  3.4 1.6 0.4 0. ]
 [5.2 3.5 1.5 0.2 0. ]
 [5.2 3.4 1.4 0.2 0. ]
 [4.7 3.2 1.6 0.2 0. ]
 [4.8 3.1 1.6 0.2 0. ]
 [5.4 3.4 1.5 0.4 0. ]
 [5.2 4.1 1.5 0.1 0. ]
 [5.5 4.2 1.4 0.2 0. ]
 [4.9 3.1 1.5 0.1 0. ]
 [5.  3.2 1.2 0.2 0. ]
 [5.5 3.5 1.3 0.2 0. ]
 [4.9 3.1 1.5 0.1 0. ]
 [4.4 3.  1.3 0.2 0. ]
 [5.1 3.4 1.5 0.2 0. ]
 [5.  3.5 1.3 0.3 0. ]
 [4.5 2.3 1.3 0.3 0. ]
 [4.4 3.2 1.3 0.2 0. ]
 [5.  3.5 1

In [15]:
class Question:
    def __init__(self,column, value):
        self.column = column
        self.value = value
        
    def match(self, data):
        value = data[self.column]
        return value >= self.value
    
    def __repr__(self):
        condition = ">="
        return "Is %s %s %s" % (header[self.column], condition, str(self.value))
    

In [17]:
def count_values(rows):
    count = {}
    for row in rows: 
        label = row[-1]
        
        if label not in count: 
            count[label] = 0
        count[label]+=1
    return count

In [21]:
count_values(data)

{0.0: 50, 1.0: 50, 2.0: 50}

In [23]:
def partition(rows,question): 
    true_row,false_row=[],[]
    for row in rows:
        if question.match(row):
            true_row.append(row)
        else:
            false_row.append(row)
    return true_row,false_row

In [24]:
print(Question(0,5))
#t_r represents true_rows and f_r false_rows
t_r,f_r=partition(data,Question(0,5))
#thus t_r will only contain sepal legnth values > 5cm
t_r

Is sepal_length >= 5


[array([5.1, 3.5, 1.4, 0.2, 0. ]),
 array([5. , 3.6, 1.4, 0.2, 0. ]),
 array([5.4, 3.9, 1.7, 0.4, 0. ]),
 array([5. , 3.4, 1.5, 0.2, 0. ]),
 array([5.4, 3.7, 1.5, 0.2, 0. ]),
 array([5.8, 4. , 1.2, 0.2, 0. ]),
 array([5.7, 4.4, 1.5, 0.4, 0. ]),
 array([5.4, 3.9, 1.3, 0.4, 0. ]),
 array([5.1, 3.5, 1.4, 0.3, 0. ]),
 array([5.7, 3.8, 1.7, 0.3, 0. ]),
 array([5.1, 3.8, 1.5, 0.3, 0. ]),
 array([5.4, 3.4, 1.7, 0.2, 0. ]),
 array([5.1, 3.7, 1.5, 0.4, 0. ]),
 array([5.1, 3.3, 1.7, 0.5, 0. ]),
 array([5. , 3. , 1.6, 0.2, 0. ]),
 array([5. , 3.4, 1.6, 0.4, 0. ]),
 array([5.2, 3.5, 1.5, 0.2, 0. ]),
 array([5.2, 3.4, 1.4, 0.2, 0. ]),
 array([5.4, 3.4, 1.5, 0.4, 0. ]),
 array([5.2, 4.1, 1.5, 0.1, 0. ]),
 array([5.5, 4.2, 1.4, 0.2, 0. ]),
 array([5. , 3.2, 1.2, 0.2, 0. ]),
 array([5.5, 3.5, 1.3, 0.2, 0. ]),
 array([5.1, 3.4, 1.5, 0.2, 0. ]),
 array([5. , 3.5, 1.3, 0.3, 0. ]),
 array([5. , 3.5, 1.6, 0.6, 0. ]),
 array([5.1, 3.8, 1.9, 0.4, 0. ]),
 array([5.1, 3.8, 1.6, 0.2, 0. ]),
 array([5.3, 3.7, 1.

In [25]:
def gini(rows):
    count=count_values(rows)
    impurity=1
    for label in count:
        probab_of_label=count[label]/float(len(rows))
        impurity-=probab_of_label**2
    return impurity

In [26]:
gini(data)

0.6666666666666665

In [27]:
def entropy(rows):
    entropy=0
    count=count_values(rows)
    for label in count:
        p=count[label]/float(len(rows))
        entropy-=p*np.log2(p)
    return entropy

In [28]:
entropy(data)


1.584962500721156

In [30]:
def info_gain_gini(current,left,right):
    p =float(len(left))/len(left)+len(right)
    return current-p*gini(left)-(1-p)*gini(right)

In [31]:
def info_gain_entropy(current,left,right):
    p =float(len(left))/len(left)+len(right)
    return current-p*entropy(left)-(1-p)*entropy(right)

In [32]:
def best_split_gini(rows):
    best_gain=0
    best_question=None
    current=gini(rows)
    features=len(rows[0])-1
    for col in range(features):
        values=set([row[col] for row in rows])
        for val in values:
            question=Question(col,val)
            true_rows,false_rows=partition(rows,question)
            if len(true_rows)==0 or len(false_rows) ==0:
                continue
            gain=info_gain_gini(current,true_rows,false_rows)
            if gain>=best_gain:
                best_gain,best_question=gain,question
    return best_gain,best_question

In [45]:
def best_split_entropy(rows):
    best_gain=0
    best_question=None
    current=entropy(rows)
    features=len(rows[0])-1
    for col in range(features):
        values=set([row[col] for row in rows])
        for val in values:
            question=Question(col,val)
            true_rows,false_rows=partition(rows,question)
            if len(true_rows)==0 or len(false_rows)==0:
                continue
            gain=info_gain_entropy(current,true_rows,false_rows)
            if(gain>=best_gain):
                best_gain,best_question=gain,question
    return best_gain,best_question

In [46]:
a,b=best_split_gini(data)
c,d=best_split_entropy(data)
print(a)
print(b)
print(c)
print(d)

99.99552572706934
Is petal_length >= 6.9
237.73467071046556
Is petal_length >= 6.9


In [34]:
class DecisionNode:
    def __init__(self,question,true_branch,false_branch):
        self.question = question
        self.true_branch = true_branch
        self.false_branch = false_branch

In [35]:
class Leaf:
    def __init__(self,rows):
        self.predictions=count_values(rows)


In [37]:
def build_tree(rows):
    gain,question=best_split_gini(rows)
    if gain==0:
        return Leaf(rows)
    
    true_rows, false_rows = partition(rows, question)
    true_branch = build_tree(true_rows)
    false_branch = build_tree(false_rows)
    return DecisionNode(question, true_branch, false_branch)

In [39]:
tree=build_tree(data)

In [40]:
def print_tree(node,indentation=""):
    if isinstance(node,Leaf):
        print(indentation+"PREDICTION",node.predictions)
        return 
    print(indentation + str(node.question))
    print(indentation+ "True Branch")
    print_tree(node.true_branch,indentation + " ")
    print(indentation+ "False Branch")
    print_tree(node.false_branch,indentation + " ")

In [42]:
print_tree(tree)

Is petal_length >= 6.9
True Branch
 PREDICTION {2.0: 1}
False Branch
 Is sepal_width >= 4.4
 True Branch
  PREDICTION {0.0: 1}
 False Branch
  Is sepal_width >= 4.2
  True Branch
   PREDICTION {0.0: 1}
  False Branch
   Is sepal_length >= 7.9
   True Branch
    PREDICTION {2.0: 1}
   False Branch
    Is sepal_width >= 4.1
    True Branch
     PREDICTION {0.0: 1}
    False Branch
     Is sepal_width >= 4.0
     True Branch
      PREDICTION {0.0: 1}
     False Branch
      Is petal_length >= 6.7
      True Branch
       PREDICTION {2.0: 2}
      False Branch
       Is petal_length >= 6.6
       True Branch
        PREDICTION {2.0: 1}
       False Branch
        Is petal_length >= 6.3
        True Branch
         PREDICTION {2.0: 1}
        False Branch
         Is sepal_length >= 7.7
         True Branch
          PREDICTION {2.0: 1}
         False Branch
          Is sepal_length >= 7.4
          True Branch
           PREDICTION {2.0: 1}
          False Branch
           Is petal_lengt